Repository wanted-codestates-project-team-05/wanted-codestates-project-05-08, pull requests merged in 2022-03, with the labels that each got.

#5 [Client] / #3 #4 / CORS 에러 해결, api 요청 함수 추가
  netlify.toml
  package-lock.json
  package.json
  src/service/recreationForestApi.js
  src/setupProxy.js
Labels: bug, feat

#6 Feat: 'redux store 추가'
  package-lock.json
  package.json
  src/components/Sample.js
  src/index.js
  src/store/form-slice.js
  src/store/index.js
Labels: feat

#33 [Client]/ #32 /feat: list page error handling, router, design: icon
  src/pages/List.js
  src/service/api.js
  src/setupProxy.js
Labels: component, css, feat

#42 [Client]/ #42 / design: list page loading
  src/pages/List.js
Labels: css

#45 [Client]/ #44 /fix: list page error handling bug fix
  src/pages/List.js
Labels: bug

#47 [Client] / Add search event when input is out of focus
  src/components/Button.js
  src/components/SearchInp.js
  src/pages/List.js
Labels: css, feat
